default_language_version:
    python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: debug-statements
  - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    args: [--line-length=120]
